apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flink-kubernetes-operator
  labels:
    app: flink-kubernetes-operator
    app.kubernetes.io/part-of: magnon-platform
rules:
  - apiGroups: ["flink.apache.org"]
    resources: ["flinkdeployments", "flinksessionjobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["flink.apache.org"]
    resources: ["flinkdeployments/status", "flinksessionjobs/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flink-kubernetes-operator
  labels:
    app: flink-kubernetes-operator
    app.kubernetes.io/part-of: magnon-platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flink-kubernetes-operator
subjects:
  - kind: ServiceAccount
    name: flink-kubernetes-operator
    namespace: flink-operator
