apiVersion: v1
kind: ResourceQuota
metadata:
  name: flink-operator-quota
  namespace: flink-operator
  labels:
    app.kubernetes.io/part-of: magnon-platform
    magnon.io/project: substrate
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 20Gi
    limits.cpu: "40"
    limits.memory: 80Gi
    pods: "100"
