apiVersion: v1
kind: ServiceAccount
metadata:
  name: flink-kubernetes-operator
  namespace: flink-operator
  labels:
    app: flink-kubernetes-operator
    app.kubernetes.io/name: flink-kubernetes-operator
    app.kubernetes.io/part-of: magnon-platform
    magnon.io/project: substrate
