apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flink-operator

resources:
  - ../../base

commonLabels:
  environment: staging

patches:
  - target:
      kind: Deployment
      name: flink-kubernetes-operator
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: staging

images:
  - name: ghcr.io/project-substrate/flink-kubernetes-operator
    newTag: staging
